name: Local Config
version: 1.0.0
schema: v1
models:
  - name: Qwen 2.5 Coder 7b
    provider: ollama
    model: qwen2.5-coder:7b
    roles:
      - edit
      - apply
      - autocomplete
    temperature: 0.2
    contextLength: 4096
  - name: Qwen 2.5 Coder 7b Chat
    provider: ollama
    model: qwen2.5-coder:7b
    roles:
      - chat
    temperature: 0.7
